### ISSUE TITLE
Div issues

### ISSUE THREAD

**Issue by RamshackleJohnny** [AlaaA0813/more-css-practice#1]
https://github.com/AlaaA0813/more-css-practice/blob/5c63032fd8f2e590c38fe1cbc7f5185cde7814ac/amazon/index.html#L22
To separate the images into two even rows, i'd suggest wrapping 4 and 4 of them in divs, so open divs on lines 23 and 40 and close on 39 and 56

Also I think you forgot to close your last div

**Comment by zachfedor** [comment]
@RamshackleJohnny That is a good idea _if_ you wanted the rows to be even. But what if the browser is smaller and can only show 3 in a row. By separating all of the blocks into 2 rows of 4, you create the possibility of something looking like this:
```
1   2   3
4
5   6   7
8
```
Which is probably not what we want. Remember: we don't have control of how our users view our content, so we have to stay fluid to be able to handle all of them.
